### PR TITLE
FDM: a few fixes on prop files and 65 hp engine file

### LINKED ISSUE #3: A few fixes on engines and propeller files
The propeller files were all for 75" diameter (instead of 74" and 75").
Engine  `<minmp unit="INHG"`> has been deleted, which gives a too low RPM with throttle = 0 (OK at default = 0.2), the 65 hp engine stops running.
@wlbragg, see [JSBSim Engines](http://wiki.flightgear.org/JSBSim_Engines#Parameter_definitions) 
**minmp** is for the effective idle RPM at 0 throttle,

> **idlerpm**: this value affects the throttle fall off and the engine stops running if it is slowed below 80% of this value. The engine starts running when it reaches 80% of this value. 

I've added the minmp for the 65 hp engine, but it is still possibly to adjust (to do at throttle = 0).
I haven't checked the 95 hp and 150 hp engines. I let you do.

PR is to come.

### PR DESCRIPTION
**Pull request by dany93**
Fixes #3

### CODE REVIEW

**Comment by wlbragg** [comment]
@dany93 
OK, we start here. I'll do some testing tonight on all three regimes and see where were at.

I'm going to push these changes to fgaddon as well, beings I messed up the last changes so badly. It will be a good place to leave fgaddon while we continue to improve upon this.
Thank you!

**Comment by wlbragg** [comment]
Any changes from here on we can do in a new PR but i will wait to merge anything new until were completely satisfied.
I want these particular changes in now so anyone pulling from master will have something sane.

**Comment by wlbragg** [comment]
@dany93 
Question, I wasn't totally sure I understood the use of minmp, so at 0 throttle this number needs to be set for the RPM to match the spec?
As in, the 95 hp engine says idle RPM = 700, so the minmp should be set so the engine actually idles at 700 at 0 throttle?

**Comment by wlbragg** [comment]
@dany93 
OK, I think I got this set to a sane starting point.

It does appear volumetric-efficiency can be adjusted to tune engine performance according to jsbsim docs?
>The volumetric efficiency in JSBSim atmospheric engines is at 0.85 per default.
It is at 0.95 or 0.8 or 0.78 or I don't know what in the J3Cub. It must be at 0.85 in normal conditions, otherwise the engine power in wrong, too low, too high, or the connection between throttle, power, RPM is wrong.
Which means that the previous tests made with these values may be not valid.

What can you tell me about it and how it should work? Why .85 as a default?

**Comment by dany93** [comment]
@wlbragg 
```
  <minmp unit="INHG">
  <idlerpm> 
```
What I would do, to the set idle RPM = 700:
- set **minmp** in the engine file such as RPM = 700 in the sim **with throttle = 0** (not with Throttle = 0.2 as per default).
I see no other way than trial and error, unfortunately. You can help by reading the` map_inhg` property, but that may not be very accurate.
An idle RPM slightly lower than 700 at rest on the runway may be realistic, we often slightly push the throttle before or after engine start. Otherwise, the engine vibrates and is noisy. But in descending flight, it will hold.
- set **idlerpm** at or slightly lower than 700. Like this, it should stop running at 700 * 80% = 560 RPM.

**Comment by dany93** [comment]
> What can you tell me about it and how it should work? Why .85 as a default?

I don't know why 0.85 is the magic number. However, I think that is has a realistic justification.
I think that this ratio is for taking into account that, as the gas is aspired into the cylinders, 1 liter of _mechanical cylinder displacement_ does not give the fitting _**mass** of air at atmospheric pressure_ (a bit less). Also possibly for taking into account incompletely burn t fuel?

For a boosted engine (with a supercharger, which introduces compressed air, above atmospheric pressure) this value is above 1. There is more air for 1 liter of cylinder displacement than in 1 liter of air at atmospheric pressure.

I don't think that the `volumetric-efficiency` is for tuning engine performance. Although it does have such an effect. However, it must be used while understanding well what it does (e.g. as a cheating for carb icing. The `air-intake-impedance-factor` may have been better fitted for the same effect).
As far as engine performance, the `air-intake-impedance-factor` is here to take the pressure drop across the intake system into account (in case the intake system has a bad conduction, poorer than "normal"). 

At least, this is how I "understand" it...

**Comment by wlbragg** [comment]
> However, it must be used while understanding well what it does (e.g. as a cheating for carb icing. The air-intake-impedance-factor may have been better fitted for the same effect).

Good to know, that makes more sense to me as well. We should suggest this in the c172p and see what the reasoning for using volumetric-efficiency was.

That explains why there is a also an entry in engine.nas.
There is also a line in autostart that could need to be accounted for it they are ever changed. Of course autostart by design is designed to clean everything and start fresh.

One more question about volumetric-efficiency changing for the 95 and 150. I didn't totally understand if the "magic number" of .85 should apply to all three engines. Or do you think there is some basis for a higher efficiency number for a larger bore/engine?

**Comment by dany93** [comment]
> do you think there is some basis for a higher efficiency number for a larger bore/engine?

I don't think so.
Up to the C172, I never minded about this value, never changed it. [Aeromatic](http://jsbsim.sourceforge.net/aeromatic2.html) (the simplified engine script for JSBSim) sets it at 0.85 for piston engines per default.
I'm strongly think (not sure, but not far) that this number does not depend on the engine power. For non-boosted engines, atmospheric ones.

**Comment by wlbragg** [comment]
Also I had it backwards, they were using lower efficiency for larger bores.

**Comment by wlbragg** [comment]
Arggg, I did all my testing at .95 volumetric-efficiency because that is what engine.nas was defaulting to for the carb icing regardless of whether or not you were using it in the UI.

**Pull request merged**
